const express = require('express')
const authController = require("../controllers/auth.controller")

const authRouter = express.Router()

// this is a type of comment, which is used to describe the api, which we are going to create, this is called swagger documentation, and this is used to generate the documentation for our api, so that we can easily understand the api, and we can easily use the api, without looking at the code, we can easily understand the api, by looking at the documentation, which is generated by swagger, so this is a very good practice to write the documentation for our api
// this type of comment is used by IDE's like vs code for documentation purpose 
// we write description about the function in this comment, and whenever we'll hover pn the name of that function anywhere in the code, we'll be able to see that written description
/**
 * @route POST /api/auth/register
 * @description Register a new user
 * @access Public
 */

authRouter.post("/register", authController.registerUserController)


module.exports = authRouter