const express = require('express')
const authController = require("../controllers/auth.controller")
const authMiddleware = require("../middlewares/auth.middleware")

const authRouter = express.Router()

// this is a type of comment, which is used to describe the api, which we are going to create, this is called swagger documentation, and this is used to generate the documentation for our api, so that we can easily understand the api, and we can easily use the api, without looking at the code, we can easily understand the api, by looking at the documentation, which is generated by swagger, so this is a very good practice to write the documentation for our api
// this type of comment is used by IDE's like vs code for documentation purpose 
// we write description about the function in this comment, and whenever we'll hover pn the name of that function anywhere in the code, we'll be able to see that written description
/**
 * @route POST /api/auth/register
 * @description Register a new user
 * @access Public
 */

authRouter.post("/register", authController.registerUserController)

/**
 * @route POST /api/auth/login
 * @description login user with email and password
 * @access Public
 */

authRouter.post("/login", authController.loginUserController)

// now, creating an another api for logout, which will be used to logout the user, and this api will be protected, means only authenticated user can access this api, and this api will remove the token from the cookies, and also add that token in the blacklist, so that it cannot be used again
/**
 * @route GET /api/auth/logout
 * @description clear the token from cookies and add that token in blacklist, so that it cannot be used again
 * @access public   // note, public access rkhne mein chances hote hai ki token kabhi na mile, aise mein hm bs cookie ko clear kr dege, token blacklist nahi karege
 */

authRouter.get("/logout", authController.logoutUserController)

// creating another api, get-me => which will be used to get the details of the logged in user, and this api will be protected, means only authenticated user can access this api(this we will implement using a middleware, jo btayega ki kis user ki taraf se request aa rhi hai, and vo user logged in hai ya nahi), 
// and this api will return the details of the logged in user

/**
 * @route GET /api/auth/get-me
 * @description Get the current logged in user's details
 * @access Private
 */

authRouter.get("/get-me", authMiddleware.authUser, authController.getMeController)  



module.exports = authRouter